project:
  type: website

website:
  title: "Youssef DIR"
  navbar:
    title: false
    logo: "logo.png"
    left:
      - href: index.qmd
        text: Accueil
      - href: index.qmd#projects 
        text: Projets
    right:
      - href: cvdata.pdf
        text: Resume

format:
  html:
    html-head-include: |
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Aboreto&display=swap">
    theme: Lux
    css: styles.css
    sidebar: false
    toc: false
    extra_dependencies:
      - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css