project:
  type: website

website:
  title: "Youssef DIR"
  navbar:
    left:
      
      
      - href: index.qmd
        text: Accueil
      - href: about.qmd
        text: Projets
        
    # Supprimez la section "Mes Projets" de la barre de navigation
    # right: 
    #   - href: projets.qmd
    #     text: Mes Projets

format:
  html:
    theme: Lux
    dark: darkly
    css: styles.css
    sidebar: false
    toc: false
    extra_dependencies:
      - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css



