[build]
  # Commande d'installation pour Quarto
  command = "curl -fsSL https://quarto.org/download/latest/ | bash && quarto render"
  
  # Dossier où le site généré sera publié
  publish = "_site"

[build.environment]
  # Spécifier la version de Quarto à installer (optionnel si déjà pris en compte par l'installation)
  QUARTO_VERSION = "1.2.0"
